-- SQL schema for HMPS CMS minimal
CREATE DATABASE IF NOT EXISTS hmps_db;
USE hmps_db;
CREATE TABLE IF NOT EXISTS divisi (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  description TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS program (
  id INT AUTO_INCREMENT PRIMARY KEY,
  divisi_id INT,
  title VARCHAR(255),
  description TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (divisi_id) REFERENCES divisi(id) ON DELETE SET NULL
);
CREATE TABLE IF NOT EXISTS struktur (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(200),
  role VARCHAR(150),
  photo VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS galeri (
  id INT AUTO_INCREMENT PRIMARY KEY,
  filename VARCHAR(255),
  caption VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
